name: Run Shell Script

on:
  push:
    branches:
      - main

jobs:
  run-script-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shell script
        run: ./execute.sh
